---
apiVersion: v1
kind: Namespace
metadata:
  name: gitops
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argo-ingress
  namespace: gitops
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`argocd.internal.francesco-lombardo.it`)
    kind: Rule
    services:
    - name: argocd-server
      port: 80
  - kind: Rule
    match: Host(`argocd.internal.francesco-lombardo.it`) && Headers(`Content-Type`, `application/grpc`)
    priority: 11
    services:
    - name: argocd-server
      port: 80
      scheme: h2c
  tls:
    secretName: argocd-certificate
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: argocd
  namespace: kube-system
spec:
  repo: https://argoproj.github.io/argo-helm
  chart: argo-cd
  targetNamespace: gitops
  valuesContent: |-
    global:
      domain: argocd.internal.francesco-lombardo.it
      logging:
        format: json
        level: info
    configs:
      params:
        server.insecure: true
      # credentialTemplates:
      #   github-app-creds:
      #     url: https://github.com/argoproj
      #     githubAppID: 1
      #     githubAppInstallationID: 2
      #     githubAppEnterpriseBaseUrl: https://ghe.example.com/api/v3
      #     githubAppPrivateKey: |
      #       -----BEGIN OPENSSH PRIVATE KEY-----
      #       ...
      #       -----END OPENSSH PRIVATE KEY-----
