---
# Docker Engine options
docker_repo_url: "https://download.docker.com/linux/raspbian"
docker_gpg_url: "{{ docker_repo_url }}/gpg"
docker_gpg_keyring: /usr/share/keyrings/docker-archive-keyring.gpg
docker_arch: armhf
docker_release_channel: stable
docker_repository: "deb [arch={{ docker_arch }} signed-by={{ docker_gpg_keyring }}] {{ docker_repo_url }} {{ ansible_distribution_release }} {{ docker_release_channel }}"

docker_deamon_options: {}

# Docker Service options
docker_service_state: started
docker_service_enabled: true 

