---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    ports:
      web:
        redirectTo:
          port: websecure
      traefik:
        expose: true
    # Create an IngressRoute for the dashboard
    ingressRoute:
      dashboard:
        enabled: true
        # Custom match rule with host domain
        matchRule: PathPrefix(`/api`, `/dashboard`)
        entryPoints: ["traefik"]
    providers:
      kubernetesCRD:
        enabled: true
        allowCrossNamespace: true

