---

- name: Install Docker Engine
  apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: yes
  notify:
    - Restart Docker

- name: Ensure Docker directory exists (docker deamon options specified)
  file:
    path: /etc/docker
    state: directory
    mode: 0755
  when: docker_deamon_options.keys() | length > 0

- name: Configure docker deamon
  copy:
    content: "{{ docker_deamon_options | to_nice_json }}"
    dest: /etc/docker/deamon.json
    mode: 0644
  when: docker_deamon_options.keys() | length > 0
  notify:
    - Restart Docker

- name: Ensure Docker is started and enabled at boot
  service:
    name: docker
    state: "{{ docker_service_state }}"
    enabled: "{{ docker_service_enabled }}"

- name: Install Docker Compose
  pip:
    name: docker-compose
